management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Homework3
    description: This is my spring boot application
    version: 1.0.0