management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Homework4
    description: This is my spring boot application
    version: 2.0.0

server:
  port: 8081